apiVersion:  k3d.io/v1alpha5
kind: Simple
metadata:
  name: demo-cluster
servers: 1 # Control plane nodes.
agents: 3 # Data plane nodes.
# Enable Ingress to expose services.
ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer
  - port: 8443:443
    nodeFilters:
      - loadbalancer
# Set node labels.
options:
  k3s:
    nodeLabels:
      - label: compute_type=expensive
        nodeFilters:
          - agent:1